import type { ProjectItem } from "@/types/project"

export const PROJECTS_ITEMS: ProjectItem[] = [
    {
        screenshot: "/projects/motion.png",
        title: "motion",
        tags: [
            "Fullstack",
            "Next.js",
            "Tailwind CSS",
            "Zustand",
            "Convex",
            "Clerk",
        ],
        liveLink: "https://portfolio-motion-app.vercel.app",
        repoLink: "https://github.com/aymenghris/motion-app",
    },
    {
        screenshot: "/projects/lingo.png",
        title: "lingo",
        tags: [
            "Fullstack",
            "Next.js",
            "Tailwind CSS",
            "Zustand",
            "React Admin",
            "Drizzle ORM",
            "Clerk",
            "Zod",
        ],
        liveLink: "https://portfolio-lingo-app.vercel.app",
        repoLink: "https://github.com/aymenghris/lingo-app",
    },
    {
        screenshot: "/projects/docs.png",
        title: "docs",
        tags: [
            "Fullstack",
            "Next.js",
            "Tailwind CSS",
            "Zustand",
            "TipTap",
            "Convex",
            "Clerk",
            "LiveBlocks",
        ],
        liveLink: "https://portfolio-docs-app.vercel.app",
        repoLink: "https://github.com/aymenghris/docs-app",
    },
    {
        screenshot: "/projects/nike-landing-page.png",
        title: "nike - landing page",
        tags: ["Frontend", "React", "Typescript", "Tailwind CSS"],
        liveLink: "https://portfolio-nike-app.vercel.app",
        repoLink: "https://github.com/aymenghris/nike-app",
    },
    {
        screenshot: "/projects/quest-quill.png",
        title: "quest quill",
        tags: ["Frontend", "React", "Typescript", "Tailwind CSS"],
        liveLink: "https://portfolio-traveling-app.vercel.app",
        repoLink: "https://github.com/aymenghris/traveling-app",
    },
    {
        screenshot: "/projects/personal-portfolio.png",
        title: "personal portfolio",
        tags: ["Frontend", "React", "Tailwind CSS", "GSAP"],
        liveLink: "/",
        repoLink: "https://github.com/aymenghris/portfolio-personal",
    },
]
