export * from "./about"
export * from "./contact"
export * from "./footer/footer"
export * from "./header/header"
export * from "./hero"
export * from "./reviews/reviews"
export * from "./skills"
export * from "./work"
