import type { Metadata } from "next"
import { Inter } from "next/font/google"
import type { ReactNode } from "react"
import { GsapLenisProvider } from "@/components/gsap-lenis-provider"
import "./globals.css"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
    title: "Aymen Ghris - Portfolio",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.svg",
    },
}

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
})

interface RootLayoutProps {
    children: ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
    return (
        <html
            lang="en"
            className={cn(
                "scrollbar-thin",
                "scrollbar-thumb-zinc-800",
                "scrollbar-track-zinc-500",
                inter.className,
            )}
        >
            <body className="h-[200vh] scroll-smooth bg-zinc-900 text-zinc-50">
                <GsapLenisProvider>{children}</GsapLenisProvider>
            </body>
        </html>
    )
}

export default RootLayout
