import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"


export const metadata: Metadata = {
    title: "Aymen Ghris - Portfolio",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.svg',
    },
}

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={inter.className}>
        <body
        >
        {children}
        </body>
        </html>
    )
}
